apiVersion: v1
kind: Service
metadata:
  name: local-treasures-frontend-service
  labels:
    app: local-treasures-frontend
spec:
  selector:
    app: local-treasures-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
